<머신러닝의 개념>

머신러닝(Machine Learning) : 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

- 업무적으로 복잡한 조건/규칙들이 다양한 형태로 결합하고 시시각각 변하기 때문에 소프트웨어 코드로 로직을 구성하여 이를 관통하는 일정 패턴을 찾기 어려운 경우 솔루션 제공 가능 -> 숨겨진 패턴을 이용 (데이터 기반 통계적 신뢰도 강화 및 예측 오류 최소화를 위해 다양한 수학적 기법을 적용하여 패턴을 스스로 인지하고 신뢰도 있는 예측 결과 도출)

- 이러한 머신러닝의 경향으로 데이터 분석 영역이 머신러닝 기반의 예측 분석(predictive Analysis)으로 재편되고 있음.

- 데이터마이닝, 영상 인식, 음성 인식, 자연어 처리에서 발전

- 단점 : 데이터에 매우 의존적 (가비지 인, 가비지 아웃(Garbage In & Out) : 좋은 품질의 데이터를 갗추지 못한다면 머신 러닝의 수행 결과가 좋을 수 없는 것) -> 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력 = '데이터 전쟁' 


머신러닝의 분류 : 지도학습(Supervised Learning) , 비지도학습(Un-supervised Learning), 강화학습(Reinforcement Learning)

- 지도학습 : 분류(classification) , 회귀(Regression) , (+ 추천시스템, 시각/음성 감지/인지, 텍스트분석, NLP)

- 비지도학습 : 클러스터링, 차원 축소, 강화 학습


파이썬과 R 기반의 머신러닝 비교 : 
- R : 통계 전용 프로그램 언어. 다양하고 많은 통계 패키지 보유
- 파이썬 : 다양한 영역에서 사용 가능. 직관적인 문법과 객체지향과 함수형 프로그래밍 모두 포괄하는 유연한 프로그래밍 아키텍쳐, 다양한 라이브러리 등 

[파이썬을 더 선호하는 이유]
- 쉽고 뛰어난 개발 생산성으로 활용도 높음
- 오픈 소스 계열의 지지가 많고, 많은 라이브러리로 인해 높은 생산성 보장 가능
- 속도는 느리지만 다양한 영역에서 사용 가능 (확장성, 유연성, 호환성)
- 엔터프라이즈 아키텍쳐의 확장 및 다양한 기업 환경으로의 확산 가능

<넘파이>

파이썬에서 선행대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지 

- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 함 -> 빠른 배열 연산
- 다양한 데이터 핸들링 기능 (그러나 판다스의 편리성에는 미치지 못함 - 판다스를 더 많이 사용)
- 많은 머신러닝 알고리즘의 기반이 되고, 입력 데이터와 출력 데이터의 배열 타입이 됨. 또한 판다스와 같은 데이터 핸들링 패키지를 이해하는 데에도 많은 도움이 됨. 

In [109]:
import numpy as np

<ndarray>

넘파이 기반의 데이터타입 
- 다차원(multi_dimension) 배열을 쉽게 생성하고 다양한 연산 수행 가능
- shape : 크기(행과 열의 수)를 튜플 형태로 가지고 있음 -> 차원까지 알 수 있음 (차원의 차이를 이해하는 것은 오류를 막기 위해 매우 중요)

In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1 : {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,
                                                            array2.ndim, array3.ndim))

array1 : 1차원, array2: 2차원, array3: 2차원


ndarray의 데이터타입

숫자 값 (int형, unsigned int형, float형, complex타입),
문자열 값,
불 값

- ndarray 내의 데이터 타입은 같은 데이터 타입만 가능! 

In [7]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [9]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


arange,zeros,ones

- arange() : 파이썬의 range()와 유사. array를 range로 표현. 0부터 함수 인자 값 -1까지의 값을 순차적으로 데이터값으로 변화
- zeros() : 모든 값을 0으로 채운 shape을 가진 ndarray로 변화
- ones() : 모든 값을 1로 채운 shape을 가진 ndarray로 변화

In [17]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [25]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape()

- ndarray를 특정 차원의 크기로 변환 - 변환을 원하는 크기를 함수 인자로 부여
- -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape으로 변환 가능 -> reshape(-1,1)로 자주 사용 (ndarray가 어던 형태라도 2차원이며, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장)

In [27]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [33]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [35]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [39]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]
array5 shape: (10, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


데이터 세트 선택하기 - 인덱싱(Indexing)

- 특정 데이터만 추출 : 원하는 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨
- 슬라이싱 : 연속된 인덱싱의 ndarray 추출 -> ':' 기호 사이에서 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 (종료인덱스-1) 위치에 있는 데이터의 ndarray 반환
- 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치의 ndarray를 반환
- 불린 인덱싱 : T/F 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

In [120]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [45]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [47]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [51]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [55]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [57]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [59]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [61]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [63]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [65]:
array1d = np.arange(start=1,stop=10)

#[]안에 arange1d > 5 Boolean indexing 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과:', array3)

array1d > 5 불린 인덱싱 결과: [6 7 8 9]


In [67]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [69]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [75]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


sort() argsort()

- np.sort() (넘파이에서 sort() 호출 -> 원 행렬은 그대로 유지한 채로 원 행렬의 정렬된 행렬을 반환), ndarray.sort() (행렬 자체에서 sort() 호출 -> 반환 값은 None)
- argsort() : 정렬된 행렬의 인덱스를 반환 - 활용도가 높음 (반환된 인덱스를 팬시 인덱스로 적용해 추출 가능 - 넘파이의 데이터 추출에서 많이 사용)

In [79]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray,sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [81]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [83]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [85]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)

print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [87]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]

print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [89]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [91]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

행렬 내적(행렬 곱)

- np.dot 이용

전치 행렬 : 행과 열의 위치를 교환한 원소로 구성한 행렬 

In [93]:
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [95]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
