# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [27]:
zero_3 = np.zeros(10)
print(zero_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [28]:
array_4 = np.array([1,2,3])
print(array_4.nbytes)

24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
zero_5 = np.zeros(10)
zero_5[4]=1
print(zero_5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector_6 = np.arange(10,50)
print(vector_6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector_7 = np.array([1,2,3])
vector_7_desc = vector_7[::-1]
print(vector_7_desc)

[3 2 1]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix_8 = np.arange(0,9).reshape(3,3)
print(matrix_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
array_9 = np.array([1,2,0,0,4,0])
print(np.nonzero(array_9))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [15]:
matrix_10_1 = np.identity(3)
print(matrix_10_1)

matrix_10_2 = np.eye(3)
print(matrix_10_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [30]:
array_11 = np.random.random((3,3,3))
print(array_11)

[[[0.10169595 0.95116971 0.33684795]
  [0.20743592 0.69766455 0.64633228]
  [0.56074404 0.68632302 0.32558697]]

 [[0.16174639 0.87009744 0.84191356]
  [0.28653629 0.24841112 0.71998797]
  [0.47021913 0.33138357 0.03485129]]

 [[0.81758502 0.65834138 0.96817615]
  [0.60342864 0.84119947 0.51779367]
  [0.74194701 0.89566527 0.64481581]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [31]:
array_12 = np.random.random((10,10))
print(array_12)
print(array_12.min())
print(array_12.max())

[[0.32495006 0.01922033 0.44810704 0.74518314 0.10180415 0.98472053
  0.74509681 0.90900235 0.66883001 0.61564634]
 [0.63394497 0.2257246  0.05105628 0.98145513 0.52996711 0.60447704
  0.39077885 0.4660487  0.97090116 0.35641114]
 [0.02875146 0.8871516  0.80691667 0.45176904 0.8603528  0.69180382
  0.7777667  0.33323074 0.58803096 0.16313066]
 [0.16919814 0.84324164 0.18268277 0.0730196  0.01477173 0.05384481
  0.08516685 0.02621968 0.04745807 0.39912836]
 [0.19739933 0.13398802 0.32361045 0.23283796 0.01932268 0.53640951
  0.58400889 0.59763472 0.26786304 0.16317111]
 [0.24216618 0.44340157 0.27509335 0.59000831 0.89344431 0.5960065
  0.42618299 0.94074063 0.33689101 0.54666317]
 [0.04489679 0.15809016 0.61605705 0.4804752  0.57429237 0.23804877
  0.51380894 0.6657549  0.83265985 0.27143166]
 [0.60352556 0.24333043 0.02498435 0.59824692 0.32323765 0.29439155
  0.86293052 0.38140907 0.80364149 0.38814244]
 [0.70887898 0.8364404  0.20678647 0.79574635 0.93736595 0.0815257
  0.89725463 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [32]:
vector_13 = np.random.random(30)
print(vector_13)
print(vector_13.mean())

[0.46490201 0.2702434  0.78745958 0.20150921 0.23470042 0.65350354
 0.01431604 0.41637208 0.5856019  0.99635139 0.19558068 0.93613022
 0.32309129 0.44070479 0.67390501 0.5850681  0.13014213 0.67780351
 0.92464836 0.31124913 0.58281223 0.17629134 0.99074314 0.19877291
 0.76353938 0.44315377 0.08487474 0.3773419  0.22907805 0.66701297]
0.47789677393791213


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
array2d_14 = np.ones((5,5))
array2d_14[1:-1,1:-1] = 0
print(array2d_14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [21]:
matrix_16 = np.diag([1,2,3,4],k=-1)
print(matrix_16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
matrix_17 = np.zeros((8,8))
matrix_17[1::2,::2] = 1
matrix_17[::2,1::2] = 1
print(matrix_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [35]:
array_18 = np.unravel_index(99,(6,7,8))
print(array_18)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [37]:
random_19 = np.random.random((5,5))
mean_19 = np.mean(random_19)
standard_19 = np.std(random_19)
normalized_19 = (random_19 - mean_19) / standard_19
print(normalized_19)

[[-0.38194715  0.63732413  2.2895777   0.33965521 -0.23945766]
 [-1.04681621 -0.19387555 -0.64239052  2.21190885 -1.0196089 ]
 [-0.30511947  1.17036785 -0.95658886  1.32086221 -1.44480641]
 [-0.89418381  0.54192653 -0.10141636 -1.29713254  0.34749416]
 [-0.88103295 -0.10809078  0.62092022  0.8111896  -0.77875929]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [41]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-41-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
