#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [15]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print('matrix_A :\n',A)
print('matrix_B :\n',B)
print('A X B :\n',np.dot(A,B))

matrix_A :
 [[0.6745296  0.62847291 0.08862046]
 [0.10514472 0.66858046 0.97410266]
 [0.60245457 0.66723471 0.34995264]
 [0.82081162 0.15149997 0.07084944]
 [0.60774071 0.02057016 0.50778283]]
matrix_B :
 [[0.09275444 0.50629681]
 [0.50342373 0.1158441 ]
 [0.13001539 0.12734218]]
A X B :
 [[0.39047582 0.42560219]
 [0.47298024 0.25472989]
 [0.43728136 0.42687976]
 [0.16161412 0.4421468 ]
 [0.13274574 0.37474229]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
import numpy as np

array_22 = np.arange(10)
array_22[(array_22>3)&(array_22<8)] *= -1
print(array_22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> legal 3,6->illegal

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

array(nan)
error
value error

In [4]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-4-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-4-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-4-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [19]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_value = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print(common_value)

Z1: [5 7 2 5 3 6 7 2 5 4]
Z2: [9 2 7 1 2 2 5 2 7 1]
[2 5 7]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False (emath를 사용하면 복소수 연산이 가능하지만 np.sqrt(-1)는 연산이 불가능하다)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [12]:
date28 = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(date28)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [22]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-40.5


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [23]:
array_30=np.random.uniform(0,10,5)
print(array_30//1)

[7. 4. 9. 6. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
matrix_31=np.random.randint(0,5,25).reshape((5,5))
print(matrix_31)

[[1 4 3 2 0]
 [0 1 0 0 2]
 [1 4 2 3 1]
 [2 4 0 4 1]
 [3 0 1 2 1]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [11]:
vector_32=np.random.randint(1,11,10)
print(vector_32)
print(np.sort(vector_32))

[ 2  7  9  2  3  7  2  7  4 10]
[ 2  2  2  3  4  7  7  7  9 10]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [24]:
random_A = np.random.randint(0,2,5)
random_B = np.random.randint(0,2,5)

print(np.array_equal(random_A,random_B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [26]:
import numpy as np

cartesian = np.random.randn(10, 2)

r = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])

print("Cartesian Coordinates (x, y):\n", cartesian)
print("\nPolar Coordinates (r, θ):\n", np.column_stack((r, theta)))

Cartesian Coordinates (x, y):
 [[ 0.90236542  0.03825197]
 [ 0.1289238   0.00741982]
 [ 0.59647518  1.17030124]
 [-1.06200754  0.00694062]
 [ 0.21814572 -0.81199841]
 [ 0.55469851  0.50839321]
 [-1.11567483 -0.20070846]
 [ 0.52908865  0.84049114]
 [-0.40883517  0.66669832]
 [-0.40167229 -1.15265863]]

Polar Coordinates (r, θ):
 [[ 0.90317582  0.04236541]
 [ 0.12913713  0.05748858]
 [ 1.31354011  1.09943742]
 [ 1.06203022  3.13505737]
 [ 0.84079069 -1.3083405 ]
 [ 0.75243212  0.74186848]
 [ 1.13358467 -2.96359783]
 [ 0.99315666  1.00896805]
 [ 0.78206959  2.12088239]
 [ 1.22064022 -1.9061116 ]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [27]:
Z = np.random.randint(0,10,10)
Z[Z.argmax()] = 0
print(Z)

[6 3 6 0 7 8 5 0 1 0]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [25]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance=np.abs(Z-v)

closest_index=np.argmin(distance)
Z[closest_index]

68

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [28]:
import numpy as np

Z = np.arange(9).reshape(3, 3)

print("Using np.ndenumerate():")
for index, value in np.ndenumerate(Z):
    print(index, value)

print("\nUsing np.ndindex():")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

Using np.ndenumerate():
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

Using np.ndindex():
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [29]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 8. 0.]
 [0. 0. 8.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [31]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,0])]

[[7 2 8]
 [7 0 2]
 [7 4 0]]


array([[7, 2, 8],
       [7, 0, 2],
       [7, 4, 0]])

In [32]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,1])]

[[7 2 9]
 [9 3 8]
 [3 5 5]]


array([[7, 2, 9],
       [9, 3, 8],
       [3, 5, 5]])

In [33]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[np.argsort(Z[:,2])]

[[5 1 9]
 [7 4 3]
 [7 0 6]]


array([[7, 4, 3],
       [7, 0, 6],
       [5, 1, 9]])